### ISSUE TITLE
Exception encountered when running client.py with scoring = true

### ISSUE THREAD

**Issue by rayleeriver** [augerai/a2ml#161]
Exception encountered with Downloaded Auger Model when running with client.py script.

**Steps to Reproduce the Issue**
1. Download model from Auger.ai
2. Unzip downloaded export_XXXXX.zip 
3. run:  python3 client.py --path_to_predict callout_test.csv --score true

**Environment Details:**
 - OS: Ubuntu 18.04
 - A2ML Version: 0.3.6
 - Python Version: 3.7.5
 - auger-hub-api-client: 0.6.8
 - auger.ai.predict: 1.0.27

**Console log**

> python3 client.py  --path_to_predict callout_test.csv  --score true
Start loading model: 2020-05-13 22:36:19.916121
End loading model: 2020-05-13 22:36:19.942845
/home/vagrant/git/next-misc/next-ml/automl/predictions/callout_test_757AD3B009ED400_EAD5025C62E643A_predicted.csv
Traceback (most recent call last):
  File "client.py", line 120, in <module>
    do_score=args.score, verbose=args.verbose)
  File "client.py", line 104, in get_predictions
    predict_path=path_to_predict, predictions=predictions)
TypeError: score_by_model() got an unexpected keyword argument 'predictions'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

> Original exception was:
Traceback (most recent call last):
  File "client.py", line 120, in <module>
    do_score=args.score, verbose=args.verbose)
  File "client.py", line 104, in get_predictions
    predict_path=path_to_predict, predictions=predictions)
TypeError: score_by_model() got an unexpected keyword argument 'predictions'

**Comment by skatedplrn** [comment]
Please upgrade auger.ai.predict, I released version 1.0.39
Also you should pass --model_path parameter to client.py, if you run it inside model folder, it will be:
python3 client.py --model_path ./model --path_to_predict callout_test.csv --score true
