### ISSUE TITLE
Auger credentials for A2ML in staging and production

### ISSUE THREAD

**Issue by holyketzer** [augerai/a2ml#462]
```
resource = Pipeline.find_by(uid: '792B531999554F5')
resource.start_actuals_score_task!(
  actual_records: [
    {
      "actual": "setosa",
      "petal_length": 1,
      "petal_width": 0.1,
      "sepal_length": 5.38,
      "sepal_width": 2.96
    }
  ]
)
```

https://app-staging.auger.ai/admin/cluster_tasks/143864

```
2020-10-29T14:00:02.536679703Z [2020-10-29 14:00:02,536: INFO/MainProcess] Received task: a2ml.tasks_queue.tasks_hub_api.score_actuals_by_model_task[1232aa22-d85d-4b47-95d8-134d89dfce04]  
2020-10-29T14:00:04.954616801Z [2020-10-29 14:00:04,954: WARNING/ForkPoolWorker-30] [warning] SOCKS support in urllib3 requires the installation of optional dependencies: specifically, PySocks.  For more information, see https://urllib3.readthedocs.io/en/latest/contrib.html#socks-proxies
2020-10-29T14:00:05.495513284Z [2020-10-29 14:00:05,494: WARNING/ForkPoolWorker-30] Traceback (most recent call last):
2020-10-29T14:00:05.495538444Z [2020-10-29 14:00:05,494: WARNING/ForkPoolWorker-30] File "/app/a2ml/api/utils/decorators.py", line 4, in wrapper
2020-10-29T14:00:05.495542225Z     return decorated(self, *args, **kwargs)
2020-10-29T14:00:05.495544825Z [2020-10-29 14:00:05,494: WARNING/ForkPoolWorker-30] File "/app/a2ml/api/utils/decorators.py", line 23, in wrapper
2020-10-29T14:00:05.495560075Z     self.credentials.verify()
2020-10-29T14:00:05.495562615Z [2020-10-29 14:00:05,494: WARNING/ForkPoolWorker-30] File "/app/a2ml/api/auger/credentials.py", line 108, in verify
2020-10-29T14:00:05.495565155Z     'Please provide your credentials to Auger...')
2020-10-29T14:00:05.495567475Z [2020-10-29 14:00:05,494: WARNING/ForkPoolWorker-30] Exception: Please provide your credentials to Auger...
2020-10-29T14:00:05.495570075Z [2020-10-29 14:00:05,494: INFO/ForkPoolWorker-30] [auger]  Please provide your credentials to Auger...
2020-10-29T14:00:05.495572425Z [2020-10-29 14:00:05,495: WARNING/ForkPoolWorker-30] Traceback (most recent call last):
2020-10-29T14:00:05.495574835Z [2020-10-29 14:00:05,495: WARNING/ForkPoolWorker-30] File "/app/a2ml/api/utils/provider_runner.py", line 82, in execute_provider
2020-10-29T14:00:05.495577445Z     result = getattr(provider, operation_name)(*args, **kwargs)
2020-10-29T14:00:05.495579935Z [2020-10-29 14:00:05,495: WARNING/ForkPoolWorker-30] File "/app/a2ml/api/auger/a2ml.py", line 26, in predict
2020-10-29T14:00:05.495582385Z     model_id, filename, threshold, locally, data, columns, predicted_at, output)
2020-10-29T14:00:05.495591296Z [2020-10-29 14:00:05,495: WARNING/ForkPoolWorker-30] File "/app/a2ml/api/utils/decorators.py", line 4, in wrapper
2020-10-29T14:00:05.495594076Z     return decorated(self, *args, **kwargs)
2020-10-29T14:00:05.495596356Z [2020-10-29 14:00:05,495: WARNING/ForkPoolWorker-30] File "/app/a2ml/api/utils/decorators.py", line 23, in wrapper
2020-10-29T14:00:05.495598796Z     self.credentials.verify()
2020-10-29T14:00:05.495601106Z [2020-10-29 14:00:05,495: WARNING/ForkPoolWorker-30] File "/app/a2ml/api/auger/credentials.py", line 108, in verify
2020-10-29T14:00:05.495603636Z     'Please provide your credentials to Auger...')
2020-10-29T14:00:05.495605886Z [2020-10-29 14:00:05,495: WARNING/ForkPoolWorker-30] Exception: Please provide your credentials to Auger...
2020-10-29T14:00:05.986713420Z [2020-10-29 14:00:05,986: ERROR/ForkPoolWorker-30] Task a2ml.tasks_queue.tasks_hub_api.score_actuals_by_model_task[1232aa22-d85d-4b47-95d8-134d89dfce04] raised unexpected: Exception('Please provide your credentials to Auger...')
2020-10-29T14:00:05.986739951Z Traceback (most recent call last):
2020-10-29T14:00:05.986743011Z   File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
2020-10-29T14:00:05.986745511Z     R = retval = fun(*args, **kwargs)
2020-10-29T14:00:05.986747651Z   File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 650, in __protected_call__
2020-10-29T14:00:05.986750051Z     return self.run(*args, **kwargs)
2020-10-29T14:00:05.986752181Z   File "/app/a2ml/tasks_queue/tasks_hub_api.py", line 99, in func_wrapper
2020-10-29T14:00:05.986754351Z     result = task_func(*args, **kwargs)
2020-10-29T14:00:05.986756441Z   File "/app/a2ml/tasks_queue/tasks_hub_api.py", line 532, in score_actuals_by_model_task
2020-10-29T14:00:05.986758621Z     provider=params.get('provider')
2020-10-29T14:00:05.986776992Z   File "/app/a2ml/api/model_review/model_review.py", line 72, in add_actuals
2020-10-29T14:00:05.986779402Z     raise Exception(res['data'])
2020-10-29T14:00:05.986781442Z Exception: Please provide your credentials to Auger...
```

**Comment by holyketzer** [comment]
https://github.com/deeplearninc/hub/pull/3397
